# Generated by Django 4.2.5 on 2023-09-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('depertment', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'User_infoo',
            },
        ),
    ]
